name: client-build-deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
defaults:
   run:
     working-directory: ./client
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - name: Step 1 - checkout code branch
          uses: actions/checkout@v1

        - name: Step 2 - setup Node environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'npm'
            cache-dependency-path: client/package-lock.json

        - name: Step 3 - Npm install
          run: npm install

        - name: Step 4 - Build
          run: npm run build

        # - name: Step 5 - Deploy
        #   uses: lbertenasco/s3-deploy@v1
        #   with:
        #     folder: dist
        #     bucket: ${{ secrets.S3_BUCKET }}
        #     dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        #     invalidation: / *